import * as coreClient from "@azure/core-client";
export declare const SponsorkitDomainApiSponsorsBeneficiaryRequest: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSponsorsBeneficiaryResponse: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSponsorsBeneficiaryIdReferencePostRequest: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSponsorsBeneficiaryIdReferenceGetRequest: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSponsorsBeneficiaryIdReferenceGetResponse: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSponsorsBeneficiaryIdReferenceGetModelsDonationsResponse: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSponsorsBeneficiaryIdReferenceGetModelsSponsorSponsorsResponse: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSponsorsBeneficiaryIdReferenceGetModelsSponsorResponse: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSponsorsBeneficiaryIdReferenceGetModelsSponsorSponsorsByAmountResponse: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSponsorsBeneficiaryIdReferenceGetModelsSponsorSponsorsByDateResponse: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSignupFromGitHubRequest: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSignupFromGitHubResponse: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiSignupActivateStripeAccountUserIdRequest: coreClient.CompositeMapper;
export declare const SponsorkitDomainApiBrowserBeneficiaryIdReferenceRequest: coreClient.CompositeMapper;
//# sourceMappingURL=mappers.d.ts.map