version: '3.4'

services:
  sponsorkit:
    image: ${DOCKER_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
    - network
    ports:
    - "80:80"
    - "443:443"

networks:
  network: