// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sponsorkit.Domain.Models;

namespace Sponsorkit.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sponsorkit.Domain.Models.Bounty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountInHundreds")
                        .HasColumnType("int");

                    b.Property<Guid>("AwardedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AwardedToId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("IssueId");

                    b.ToTable("Bounties");
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EncryptedEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountInHundreds")
                        .HasColumnType("int");

                    b.Property<Guid?>("BountyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SponsorshipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StripeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BountyId")
                        .IsUnique()
                        .HasFilter("[BountyId] IS NOT NULL");

                    b.HasIndex("SponsorshipId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d5d4bc2-8b18-45c0-b48e-5d81773c2eb3"),
                            AmountInHundreds = 100,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SponsorshipId = new Guid("43029511-840f-472d-aec5-3ae45787308b"),
                            StripeId = "foo"
                        },
                        new
                        {
                            Id = new Guid("b5e19f7a-2dff-4da2-9801-19a4fc8fe460"),
                            AmountInHundreds = 250,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SponsorshipId = new Guid("43029511-840f-472d-aec5-3ae45787308b"),
                            StripeId = "foo"
                        });
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Sponsorship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MonthlyAmountInHundreds")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("SponsorId");

                    b.ToTable("Sponsorships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43029511-840f-472d-aec5-3ae45787308b"),
                            BeneficiaryId = new Guid("681c2d58-7a3f-49fb-ada8-697c06708d32"),
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "sponsorship-foo",
                            SponsorId = new Guid("9f64c8d0-d69a-4f52-a257-1332f51f4e4d")
                        });
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("681c2d58-7a3f-49fb-ada8-697c06708d32"),
                            CreatedAtUtc = new DateTime(2021, 4, 11, 1, 28, 29, 327, DateTimeKind.Utc).AddTicks(2006),
                            Name = "the-beneficiary",
                            StripeId = "foo"
                        },
                        new
                        {
                            Id = new Guid("9f64c8d0-d69a-4f52-a257-1332f51f4e4d"),
                            CreatedAtUtc = new DateTime(2021, 4, 11, 1, 28, 29, 327, DateTimeKind.Utc).AddTicks(2377),
                            Name = "the-sponsor",
                            StripeId = "foo"
                        });
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Bounty", b =>
                {
                    b.HasOne("Sponsorkit.Domain.Models.User", "AwardedTo")
                        .WithMany("AwardedBounties")
                        .HasForeignKey("AwardedToId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sponsorkit.Domain.Models.User", "Creator")
                        .WithMany("CreatedBounties")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sponsorkit.Domain.Models.Issue", "Issue")
                        .WithMany("Bounties")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Identity", b =>
                {
                    b.HasOne("Sponsorkit.Domain.Models.User", "Owner")
                        .WithMany("Identities")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Issue", b =>
                {
                    b.HasOne("Sponsorkit.Domain.Models.Repository", "Repository")
                        .WithMany("Issues")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Payment", b =>
                {
                    b.HasOne("Sponsorkit.Domain.Models.Bounty", "Bounty")
                        .WithOne("Payment")
                        .HasForeignKey("Sponsorkit.Domain.Models.Payment", "BountyId");

                    b.HasOne("Sponsorkit.Domain.Models.Sponsorship", "Sponsorship")
                        .WithMany("Payments")
                        .HasForeignKey("SponsorshipId");
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Repository", b =>
                {
                    b.HasOne("Sponsorkit.Domain.Models.User", "Owner")
                        .WithMany("Repositories")
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("Sponsorkit.Domain.Models.Sponsorship", b =>
                {
                    b.HasOne("Sponsorkit.Domain.Models.User", "Beneficiary")
                        .WithMany("AwardedSponsorships")
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sponsorkit.Domain.Models.User", "Sponsor")
                        .WithMany("CreatedSponsorships")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
