version: '3.7'

services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "amazing_dev_only_password_totally_secret_such_wow"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"