name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - uses: actions/cache@v2
      id: nuget
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: nuget

    - name: Restore with dotnet
      if: steps.nuget.outputs.cache-hit != 'true'
      working-directory: src/api
      run: dotnet restore

    - name: Build with dotnet
      working-directory: src/api
      run: dotnet build --no-restore --configuration Release

    - name: Publish with dotnet
      working-directory: src/api
      run: dotnet publish --no-restore -c Release -o ${{env.DOTNET_ROOT}}/sponsorkit

    - name: Generate deployment package
      working-directory: ${{env.DOTNET_ROOT}}/sponsorkit
      run: zip -r api.zip .

    - name: Archive API deployment package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: api
        path: ${{env.DOTNET_ROOT}}/sponsorkit/api.zip

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - uses: actions/cache@v2
      id: node_modules
      with:
        path: src/frontend/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('src/frontend/**/package.json') }}
        restore-keys: node_modules

    - name: Install packages
      if: steps.node_modules.outputs.cache-hit != 'true'
      working-directory: src/frontend
      run: npm i

    - name: Build output
      working-directory: src/frontend
      run: npm run build

    - name: Generate deployment package
      working-directory: src/frontend/public
      run: zip -r frontend.zip .

    - name: Archive API deployment package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: src/frontend/public/frontend.zip
      
  deploy:
    needs: [build-api, build-frontend]
    runs-on: ubuntu-latest

    steps:
    - name: Download API deployment package artifact
      uses: actions/download-artifact@v2
      with:
        name: api

    - name: Download frontend deployment package artifact
      uses: actions/download-artifact@v2
      with:
        name: frontend

    - name: Unpack frontend deployment package artifact
      run: unzip frontend.zip frontend

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy API
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Sponsorkit
        environment_name: sponsorkit-prod
        version_label: ${{ github.sha }}
        version_description: ${{github.SHA}}
        use_existing_version_if_available: true
        region: eu-north-1
        deployment_package: api.zip

    - name: Deploy frontend
      working-directory: frontend
      run: npx gatsby-plugin-s3 deploy