name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-api:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: n1hility/cancel-previous-runs@178b93a12fb2731212e48c2cc5b7e37b937fd339
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Github Action
      uses: actions/checkout@master

    - name: Build Docker images
      run: docker-compose build

    - name: Push Docker images
      run: docker-compose push

#    - name: Run tests
#      working-directory: src/api
#      run: dotnet test

    - name: Run staging deploy step in AWS CodePipeline
      if: github.ref == 'refs/heads/develop'
      uses: zulhfreelancer/aws-codepipeline-action@492467f78d67ac2301e55e208326a8e9fbd23284
      with:
        aws-region: eu-north-1
        aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        pipeline-name: sponsorkit-staging

    - name: Run production deploy step in AWS CodePipeline
      if: github.ref == 'refs/heads/main'
      uses: zulhfreelancer/aws-codepipeline-action@492467f78d67ac2301e55e208326a8e9fbd23284
      with:
        aws-region: eu-north-1
        aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        pipeline-name: sponsorkit-staging
