name: Build

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  release:
    types: [created]

jobs:
  build-api:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-north-1
      DOTNET_LAMBDA_PACKAGE_NAME: ${{ github.sha }}.zip
      DOTNET_LAMBDA_S3_LOCATION: sponsorkit-lambda-deploy-packages
      DOTNET_LAMBDA_FUNCTION_NAME: sponsorkit
      DOTNET_LAMBDA_FUNCTION_HANDLER: Sponsorkit
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: n1hility/cancel-previous-runs@178b93a12fb2731212e48c2cc5b7e37b937fd339
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Github Action
      uses: actions/checkout@master

    - name: Use .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install AWS .NET CLI
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: .NET Lambda build and upload to S3
      if: github.event_name != 'release' || github.event.action != 'created'
      working-directory: src/api
      run: |
        dotnet lambda package $DOTNET_LAMBDA_PACKAGE_NAME
        aws s3 cp --only-show-errors $DOTNET_LAMBDA_PACKAGE_NAME s3://$DOTNET_LAMBDA_S3_LOCATION/$DOTNET_LAMBDA_PACKAGE_NAME

    - name: Deploy to staging
      working-directory: src/api
      if: github.event_name != 'release' || github.event.action != 'created'
      run: |
        dotnet lambda deploy-function \
          --region $AWS_REGION \
          --function-name $DOTNET_LAMBDA_FUNCTION_NAME \
          --function-handler $DOTNET_LAMBDA_FUNCTION_HANDLER \
          --package $DOTNET_LAMBDA_PACKAGE_NAME

        aws lambda publish-version \
          --function-name $DOTNET_LAMBDA_FUNCTION_NAME \
          --description ${{ github.sha }}
          
    - name: Promote staging to production
      working-directory: ./src/api
      if: github.event_name == 'release' && github.event.action == 'created'
      run: |
        aws lambda update-alias \
          --function-name $DOTNET_LAMBDA_FUNCTION_NAME \
          --name production \
          --description ${{ github.sha }} \
          --function-version ${{ github.sha }}

    - name: Run tests
      working-directory: src/api
      run: dotnet test
