name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      working-directory: src/api
      run: dotnet build --configuration Release

    - name: Publish with dotnet
      working-directory: src/api
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/sponsorkit

    - name: Generate deployment package
      run: zip -r api.zip ${{env.DOTNET_ROOT}}/sponsorkit

    - name: Archive API deployment package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: api
        path: api.zip
      
  deploy:
    needs: [build-api]
    runs-on: ubuntu-latest

    steps:
    - name: Download API deployment package artifact
      uses: actions/download-artifact@v2
      with:
        name: api

    - name: Deploy API
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Sponsorkit
        environment_name: sponsorkit-prod
        version_label: ${GITHUB_SHA}
        region: eu-north-1
        deployment_package: api.zip