name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-api:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - uses: actions/cache@v2
      id: nuget
      with:
        path: |
          ~/.nuget/packages
          src/api/**/obj/**
        key: nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: nuget

    - name: Restore with dotnet
      if: steps.nuget.outputs.cache-hit != 'true'
      working-directory: src/api
      run: dotnet restore

    - name: Run tests
      working-directory: src/api
      run: dotnet test

    - name: Publish with dotnet
      working-directory: src/api
      run: dotnet publish --no-restore -c Release -o ${{env.DOTNET_ROOT}}/sponsorkit

    - name: Run deploy step in AWS CodePipeline
      uses: zulhfreelancer/aws-codepipeline-action@492467f78d67ac2301e55e208326a8e9fbd23284
      with:
        aws-region: eu-north-1
        aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        pipeline-name: Deploy
