name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      working-directory: src/api
      run: dotnet build --configuration Release

    - name: dotnet publish
      working-directory: src/api
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/sponsorkit

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '${{env.DOTNET_ROOT}}/sponsorkit'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Sponsorkit
        environment_name: sponsorkit-prod
        version_label: ${{ GITHUB_SHA }}
        region: eu-north-1
        deployment_package: deploy.zip