# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - sponsorkit-app-service(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      working-directory: src/api
      run: dotnet build --configuration Release

    - name: dotnet publish
      working-directory: src/api
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/sponsorkit

    - name: Deploy staging
      uses: azure/webapps-deploy@v2
      with:
        app-name: sponsorkit-app-service
        slot-name: staging
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_703d035de8c040339e751925f7b952ca }}
        package: ${{env.DOTNET_ROOT}}/sponsorkit

    - name: Deploy production
      uses: azure/webapps-deploy@v2
      if: github.ref == 'refs/heads/master'
      with:
        app-name: sponsorkit-app-service
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3D07F688220E42A185C6E641CC11BC7C }}
        package: ${{env.DOTNET_ROOT}}/sponsorkit

